### ISSUE TITLE
Support for secrets and tweak environment variables

### ISSUE THREAD

**Issue by ptmclean** [cfn-modules/fargate-service#7]
Hi,

I'd love to see support for secrets in the task definition. I have a few ideas on this one so I thought I'd write up an issue for discussion before any PRs.

There are a couple of things that I think could be improved together. Another thing that I have found frustrating is the limited number of environment variables you can have in the task definition. There is no way I can see to iterate through a list given as a param and create an environment variable for each. So as far as I can tell we need to give use at least one parameter per environment variable/secret. Another limitation in play here is the max number of parameters a stack can have(60). Allowing support for secrets further dilutes this balance.

At the moment each environment variables is passed using 2 parameters...
```
AppEnvironment1Key: '' # optional
AppEnvironment1Value: '' # optional
```
An idea I think might work well is to pass parameter module or a secret module rather than keys and values. This would involve...
1. Create a parameter module(I assume ssm) with an API something like this...
```
  DatabaseHostParam:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        EnvironmentKey: 'Database__Hostname'
        Name: /my-sql/connection-string'
        Value: !GetAtt 'AuroraServerlessCluster.Outputs.DnsName'
      TemplateURL: './node_modules/@cfn-modules/parameter/module.yml'
```
2. Amend the Secret module to also have an (optional) EnvironmentKey...
```
  DatabasePasswordSecret:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        EnvironmentKey: 'Database__MasterPassword'
        Name: /my-sql/password'
        KmsKeyModule: !GetAtt 'KmsKey.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/secret/module.yml'
```
3. Have this module accept these as environment variable or secrets...
```
  FargateService:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        ClusterModule: !GetAtt 'EcsCluster.Outputs.StackName'
        VpcModule: !GetAtt 'Vpc.Outputs.StackName'
        ParameterModule1: !GetAtt 'DatabaseHostParam.Outputs.StackName'
        SecretModule1: !GetAtt 'DatabasePasswordSecret.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/fargate-service/module.yml'
```
For environment variables it means users need to define an ssm parameter per environment variable but it decreases the effect of the limitation in parameters. For secrets there is little choice because you need a secrets-manager secret for each one. There is an option to use the `Name` of the secret as the environment variable key in the fargate container but I find in practice that I've wanted these to be different things. 

What do you think of the idea?
